name: CI

on:
    push:
        branches:
            - 'main'
    pull_request:

jobs:
    packages:
        name: install NPM deps
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: npm
            - name: check npm ci
              run: npm ci
    lint:
        name: run lint
        runs-on: ubuntu-latest
        needs: [packages]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: npm
            - name: npm ci
              run: npm ci
            - name: run lint
              run: npm run lint -- --max-warnings=0
    format:
        name: run format
        runs-on: ubuntu-latest
        needs: [packages]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: npm
            - name: npm ci
              run: npm ci
            - name: run format
              run: npx prettier --check .
    build:
        name: run build
        runs-on: ubuntu-latest
        needs: [packages]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: npm
            - name: npm ci
              run: npm ci
            - name: run build
              run: npm run build
            - uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist
    type-check:
        name: run type-check
        runs-on: ubuntu-latest
        needs: [packages, build]
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  cache: npm
            - name: npm ci
              run: npm ci
            - uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
            - name: run type-check
              run: npm run type-check
    test:
        name: run test
        needs: [packages, build]
        strategy:
            matrix:
                node_version: [18.x, 20.x, 21.x]
                os: [ubuntu-latest]
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: npm
            - name: npm ci
              run: npm ci
            - uses: actions/download-artifact@v4
              with:
                  name: dist
                  path: dist
            - name: run coverage test
              run: npm run coverage
            - uses: actions/upload-artifact@v4
              with:
                  name: coverage-${{ matrix.node_version }}
                  path: coverage
